#!/usr/bin/env python3
"""Build a GRB-by-GRB meeting deck for spectral-break diagnostics.

The deck is intentionally conservative: it only includes fit folders whose
spectral_plot.pdf appears to have been regenerated by the EATS-weighted
break-frequency workflow, or which contain the explicit weighted CSV marker.
This avoids mixing the legacy local-frame spectral-break diagnostic with the
new Dylan-style equal-arrival-time weighted calculation.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import math
import os
from pathlib import Path
import subprocess
import textwrap
import tomllib

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from PIL import Image, ImageChops


SHARE = Path(
    "/Users/jkeohane/Library/CloudStorage/GoogleDrive-jwkeohane@gmail.com/"
    ".shortcut-targets-by-id/1d7HnZ0yxuhMv2vPzbGBL9NNSDX9BjeDp/VegasGRBruns"
)
FITS = SHARE / "Fits"
REPORTS = SHARE / "Reports"
WORK = Path("/Users/jkeohane/GRBs/VegasJetFit/analysis/break_frequency_meeting_deck_20260527")
CACHE = WORK / "render_cache"

OUT_PDF = REPORTS / "20260527__break_frequency_meeting_deck.pdf"
OUT_MANIFEST = REPORTS / "20260527__break_frequency_meeting_deck_manifest.md"

UPDATED_AFTER = dt.datetime(2026, 5, 26, 23, 0, 0)
PAGE_SIZE = (13.333, 7.5)


FIT_CATALOG = [
    {
        "fit_type": "top_hat_on_axis",
        "display": "Top-hat on-axis wide jet",
        "run_root": FITS
        / "jet_tophat/csm_powerlaw/spectrum_dylan_smoothed/one_radian_opening_angle/"
        / "20260415__thesis_reproduction_theta1p0_thesis_reproduction_dylanphyspriors_init5pct_2000x2000_v1",
        "method": (
            "Top-hat jet; theta_c = 1 rad fixed; theta_v = 0 fixed; "
            "single power-law CSM; Dylan smoothed spectrum; seeded from Dylan best fit."
        ),
    },
    {
        "fit_type": "structured_on_axis",
        "display": "Structured power-law jet, on-axis",
        "run_root": FITS
        / "jet_structured_powerlaw/csm_powerlaw/spectrum_dylan_smoothed/thawed_core_angle/"
        / "20260423__powerlawjet_thetacfree_seeded_2000x2000_v1",
        "method": (
            "Power-law structured jet (powerlawC); theta_v = 0 fixed; theta_c thawed; "
            "s = 4, k_e = 2, k_g = 2 fixed; single power-law CSM; Dylan smoothed spectrum."
        ),
    },
    {
        "fit_type": "structured_off_axis",
        "display": "Structured power-law jet, off-axis",
        "run_root": FITS
        / "jet_structured_powerlaw/csm_powerlaw/spectrum_dylan_smoothed/thawed_viewing_angle/"
        / "20260501__anshstyle_structjet_thetavthawed_v1",
        "method": (
            "Power-law structured jet (powerlawC); theta_v thawed; theta_c fixed by setup; "
            "s = 4, k_e = 2, k_g = 2 fixed; single power-law CSM; Dylan smoothed spectrum."
        ),
    },
    {
        "fit_type": "structured_off_axis_finalprod",
        "display": "Structured power-law jet, off-axis final production",
        "run_root": FITS
        / "jet_structured_powerlaw/csm_powerlaw/spectrum_dylan_smoothed/thawed_viewing_core_and_structure/"
        / "20260521__050525A_structjet_thetav_thetac_electronp_unseeded_finalprod_10temp_5000x5000_v1",
        "method": (
            "Power-law structured jet (powerlawC); theta_v thawed; theta_c thawed; "
            "electron p thawed; 10 temperatures, 100 walkers, 5000 burn-in + 5000 production; "
            "unseeded wide-prior production run."
        ),
    },
]


DYLAN_K_CSV = Path(
    "/Users/jkeohane/GRBs/VegasJetFit/analysis/dylan_k_comparison_20260520/"
    "dylan_vs_our_k_powerlaw_tophat_onaxis_with_yerr.csv"
)
DYLAN_NMAP_CSV = Path(
    "/Users/jkeohane/GRBs/VegasJetFit/analysis/"
    "model_comparison_20260427_with_ansh_dylan_nmap_cap100_dylanorder/"
    "model_comparison_best_per_model_with_ansh_dylan_nmap_dylanorder.csv"
)


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    import csv

    if not path.exists():
        return []
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def load_dylan_maps() -> tuple[dict[str, float], dict[str, float]]:
    k_map: dict[str, float] = {}
    for row in read_csv_rows(DYLAN_K_CSV):
        try:
            k_map[row["event"]] = float(row["dylan_k"])
        except Exception:
            pass

    nmap_map: dict[str, float] = {}
    for row in read_csv_rows(DYLAN_NMAP_CSV):
        if row.get("source_owner") != "dylan_thesis":
            continue
        try:
            nmap_map[row["event"]] = float(row["nmap_value"])
        except Exception:
            try:
                nmap_map[row["event"]] = float(row["nmap"])
            except Exception:
                pass
    return k_map, nmap_map


def clean_float(value, digits=4) -> str:
    if value is None:
        return "unavailable"
    try:
        val = float(value)
    except Exception:
        return str(value)
    if not math.isfinite(val):
        return "unavailable"
    if abs(val) >= 1e4 or (abs(val) < 1e-3 and val != 0):
        return f"{val:.{digits}e}"
    return f"{val:.{digits}g}"


def get_mtime(path: Path) -> dt.datetime | None:
    if not path.exists():
        return None
    return dt.datetime.fromtimestamp(path.stat().st_mtime)


def is_new_weighted_spectral(run_dir: Path) -> bool:
    spectral = run_dir / "spectral_plot.pdf"
    if not spectral.exists():
        return False
    if (run_dir / "spectral_breaks_eats_weighted.csv").exists():
        return True
    mtime = get_mtime(spectral)
    return bool(mtime and mtime >= UPDATED_AFTER)


def read_best_json(run_dir: Path) -> dict:
    candidates = [
        run_dir / "minimized/minimized.json",
        run_dir / "minimized.json",
        run_dir / "best_fit.json",
        run_dir / "results.json",
    ]
    for path in candidates:
        if path.exists():
            try:
                return json.loads(path.read_text())
            except Exception:
                continue
    return {}


def read_toml(run_dir: Path) -> dict:
    for name in ("model.toml", "config.toml"):
        path = run_dir / name
        if path.exists():
            try:
                return tomllib.loads(path.read_text())
            except Exception:
                return {}
    return {}


def get_param(data: dict, name: str):
    params = data.get("params") or {}
    model = params.get("model") or {}
    if name in model:
        return model[name]
    if name in data:
        return data[name]
    return None


def get_sampler_summary(toml_data: dict) -> str:
    sampler = toml_data.get("sampler") or {}
    if not sampler:
        return "Sampler settings unavailable in TOML."
    fields = []
    for key in ("name", "ntemps", "num_walkers", "burn_length", "run_length", "workers"):
        if key in sampler:
            fields.append(f"{key}={sampler[key]}")
    return ", ".join(fields) if fields else "Sampler settings unavailable in TOML."


def render_pdf_first_page(src: Path) -> Path | None:
    if not src.exists():
        return None
    if src.suffix.lower() in {".png", ".jpg", ".jpeg"}:
        return crop_image_margins(src)
    CACHE.mkdir(parents=True, exist_ok=True)
    stat = src.stat()
    key = hashlib.sha1(f"{src}:{stat.st_mtime_ns}:{stat.st_size}".encode()).hexdigest()[:20]
    out_stem = CACHE / key
    out_png = CACHE / f"{key}.png"
    cropped = CACHE / f"{key}_cropped.png"
    if cropped.exists():
        return cropped
    cmd = [
        "pdftoppm",
        "-f",
        "1",
        "-l",
        "1",
        "-singlefile",
        "-png",
        "-r",
        "130",
        str(src),
        str(out_stem),
    ]
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return crop_image_margins(out_png) if out_png.exists() else None
    except Exception:
        return None


def crop_image_margins(src: Path) -> Path | None:
    """Crop near-white margins so source figures are readable on slides."""
    if not src.exists():
        return None
    CACHE.mkdir(parents=True, exist_ok=True)
    stat = src.stat()
    key = hashlib.sha1(f"crop:{src}:{stat.st_mtime_ns}:{stat.st_size}".encode()).hexdigest()[:20]
    out = CACHE / f"{key}_cropped.png"
    if out.exists():
        return out
    try:
        img = Image.open(src).convert("RGB")
        bg = Image.new("RGB", img.size, (255, 255, 255))
        diff = ImageChops.difference(img, bg).convert("L")
        mask = diff.point(lambda p: 255 if p > 12 else 0)
        bbox = mask.getbbox()
        if not bbox:
            img.save(out)
            return out
        pad = 18
        left = max(bbox[0] - pad, 0)
        top = max(bbox[1] - pad, 0)
        right = min(bbox[2] + pad, img.size[0])
        bottom = min(bbox[3] + pad, img.size[1])
        cropped = img.crop((left, top, right, bottom))
        cropped.save(out)
        return out
    except Exception:
        return src


def add_header(fig, title: str, subtitle: str | None = None):
    fig.text(0.035, 0.955, title, fontsize=22, fontweight="bold", ha="left", va="top")
    if subtitle:
        fig.text(0.035, 0.915, subtitle, fontsize=10.5, color="#444444", ha="left", va="top")


def add_footer(fig, text: str):
    fig.text(0.985, 0.018, text, fontsize=7.5, color="#666666", ha="right", va="bottom")


def add_text_box(fig, rect, text: str, title: str | None = None, fontsize=12, face="#f7f7f7"):
    ax = fig.add_axes(rect)
    ax.set_axis_off()
    ax.add_patch(plt.Rectangle((0, 0), 1, 1, facecolor=face, edgecolor="#999999", linewidth=1.2))
    y = 0.93
    if title:
        ax.text(0.04, y, title, fontsize=fontsize + 2, fontweight="bold", ha="left", va="top")
        y -= 0.1
    wrapped = []
    for para in text.split("\n"):
        if para.strip():
            wrapped.extend(textwrap.wrap(para, width=78))
        else:
            wrapped.append("")
    ax.text(0.04, y, "\n".join(wrapped), fontsize=fontsize, ha="left", va="top", color="#222222")


def add_image_box(fig, rect, src: Path | None, label: str, missing_text: str | None = None, fill: bool = False):
    ax = fig.add_axes(rect)
    ax.set_axis_off()
    ax.text(0.0, 1.02, label, fontsize=12, fontweight="bold", ha="left", va="bottom", transform=ax.transAxes)
    if src is None or not src.exists():
        ax.add_patch(plt.Rectangle((0, 0), 1, 1, facecolor="#f6f6f6", edgecolor="#aaaaaa", linewidth=1.2))
        msg = missing_text or "Missing product"
        ax.text(0.5, 0.5, "\n".join(textwrap.wrap(msg, width=52)), fontsize=13, color="#777777", ha="center", va="center")
        return

    rendered = render_pdf_first_page(src)
    if rendered is None or not rendered.exists():
        ax.add_patch(plt.Rectangle((0, 0), 1, 1, facecolor="#fff4f4", edgecolor="#aa7777", linewidth=1.2))
        ax.text(0.5, 0.5, f"Could not render:\n{src.name}", fontsize=12, color="#884444", ha="center", va="center")
        return
    try:
        img = Image.open(rendered).convert("RGB")
        ax.imshow(img, aspect="auto" if fill else None)
    except Exception as exc:
        ax.add_patch(plt.Rectangle((0, 0), 1, 1, facecolor="#fff4f4", edgecolor="#aa7777", linewidth=1.2))
        ax.text(0.5, 0.5, f"Could not load image:\n{exc}", fontsize=12, color="#884444", ha="center", va="center")


def make_slide(pdf: PdfPages, title: str, subtitle: str | None = None):
    fig = plt.figure(figsize=PAGE_SIZE, facecolor="white")
    add_header(fig, title, subtitle)
    return fig


def save_slide(pdf: PdfPages, fig):
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def discover_entries():
    dylan_k, dylan_nmap = load_dylan_maps()
    entries: list[dict] = []
    skipped: list[dict] = []

    for fit in FIT_CATALOG:
        root = fit["run_root"]
        if not root.exists():
            skipped.append({**fit, "grb": "*", "reason": "run root missing"})
            continue
        for run_dir in sorted(p for p in root.iterdir() if p.is_dir()):
            grb = run_dir.name
            spectral = run_dir / "spectral_plot.pdf"
            if not spectral.exists():
                skipped.append({**fit, "grb": grb, "reason": "spectral_plot.pdf missing"})
                continue
            if not is_new_weighted_spectral(run_dir):
                skipped.append({**fit, "grb": grb, "reason": "new EATS-weighted spectral plot not finished"})
                continue

            best = read_best_json(run_dir)
            toml_data = read_toml(run_dir)
            nmap = best.get("nmap")
            k_val = get_param(best, "k")
            entries.append(
                {
                    **fit,
                    "grb": grb,
                    "run_dir": run_dir,
                    "spectral": spectral,
                    "legacy_spectral": run_dir / "spectral_plot_legacy_before_eats_weighted.pdf",
                    "light_curve": run_dir / "light_curve.pdf",
                    "ampy_comparison": run_dir / "ampy_comparison.pdf",
                    "corner": run_dir / "corner.pdf",
                    "corner_np": run_dir / "corner_np.pdf",
                    "mass_profile": run_dir / "mass_profile.pdf",
                    "nmap": nmap,
                    "dylan_nmap": dylan_nmap.get(grb),
                    "k": k_val,
                    "dylan_k": dylan_k.get(grb),
                    "sampler": get_sampler_summary(toml_data),
                    "mtime": get_mtime(spectral),
                }
            )

    # Use Dylan thesis order where available, then alphabetical.
    dylan_order = [row.get("event") for row in read_csv_rows(DYLAN_K_CSV)]
    order_index = {event: i for i, event in enumerate(dylan_order) if event}
    entries.sort(key=lambda e: (order_index.get(e["grb"], 10_000), e["grb"], e["fit_type"]))
    skipped.sort(key=lambda e: (order_index.get(e.get("grb", ""), 10_000), e.get("grb", ""), e["fit_type"]))
    return entries, skipped


def title_text(entry: dict) -> str:
    delta = None
    if entry.get("nmap") is not None and entry.get("dylan_nmap") is not None:
        delta = float(entry["nmap"]) - float(entry["dylan_nmap"])
    return "\n".join(
        [
            f"Fit type: {entry['display']}",
            f"Run folder: {entry['run_dir'].name}",
            "",
            f"Our nmap: {clean_float(entry.get('nmap'))}",
            f"Dylan thesis/tracking-sheet nmap: {clean_float(entry.get('dylan_nmap'))}",
            f"Delta nmap (ours - Dylan): {clean_float(delta)}   [more negative nmap is better in these files]",
            "",
            f"Our k: {clean_float(entry.get('k'))}",
            f"Dylan k: {clean_float(entry.get('dylan_k'))}",
            "",
            f"Sampler: {entry.get('sampler')}",
            "",
            entry["method"],
        ]
    )


def add_status_slide(pdf: PdfPages, entries: list[dict], skipped: list[dict]):
    fig = make_slide(
        pdf,
        "Spectral Break Recalculation Status",
        "EATS = Equal-Arrival-Time Surface. Deck built from completed EATS-weighted spectral products only.",
    )
    counts = {}
    for entry in entries:
        counts[entry["display"]] = counts.get(entry["display"], 0) + 1
    skipped_counts = {}
    for item in skipped:
        if item["reason"] == "new EATS-weighted spectral plot not finished":
            skipped_counts[item["display"]] = skipped_counts.get(item["display"], 0) + 1

    lines = [
        "Interpretation point: the old spectral-break diagnostic was a local/legacy calculation and is probably not suitable for physical interpretation of nu_a, nu_m, and nu_c.",
        "The new plots use the Dylan-style EATS calculation, where EATS means Equal-Arrival-Time Surface.",
        "",
        "Included completed weighted plots:",
    ]
    if counts:
        for name, count in sorted(counts.items()):
            lines.append(f"- {name}: {count}")
    else:
        lines.append("- none")
    lines.extend(["", "Skipped because the new weighted spectral plot was not finished yet:"])
    if skipped_counts:
        for name, count in sorted(skipped_counts.items()):
            lines.append(f"- {name}: {count}")
    else:
        lines.append("- none")
    lines.extend(
        [
            "",
            "Caveat: Dylan thesis light-curve and spectral-break panels were not found as standalone local files during this build. Placeholder panels are included so the deck structure is ready once those panels are added.",
        ]
    )
    add_text_box(fig, [0.08, 0.12, 0.84, 0.72], "\n".join(lines), fontsize=13)
    add_footer(fig, f"Built {dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    save_slide(pdf, fig)


def build_deck(entries: list[dict], skipped: list[dict]):
    REPORTS.mkdir(parents=True, exist_ok=True)
    WORK.mkdir(parents=True, exist_ok=True)
    with PdfPages(OUT_PDF) as pdf:
        fig = make_slide(
            pdf,
            "GRB Spectral Break Diagnostics",
            "Old local/legacy break-frequency plots versus new Dylan-style EATS-weighted products; EATS = Equal-Arrival-Time Surface",
        )
        add_text_box(
            fig,
            [0.08, 0.16, 0.84, 0.68],
            (
                "Purpose: show how the spectral-break plots used for interpretation change when we replace the legacy/local diagnostic with the Dylan-style EATS-weighted calculation. EATS = Equal-Arrival-Time Surface.\n\n"
                "Organization: GRB by GRB, then fit type. Each included fit has a completed new spectral_plot.pdf according to timestamp or explicit weighted-output marker.\n\n"
                "Meeting use: the last slide for each fit leaves space for science notes from discussion."
            ),
            fontsize=15,
        )
        add_footer(fig, str(OUT_PDF))
        save_slide(pdf, fig)

        add_status_slide(pdf, entries, skipped)

        current_grb = None
        for entry in entries:
            if entry["grb"] != current_grb:
                current_grb = entry["grb"]
                fig = make_slide(pdf, f"{current_grb}", "GRB section divider")
                grb_entries = [e for e in entries if e["grb"] == current_grb]
                lines = [
                    f"Dylan k: {clean_float(entry.get('dylan_k'))}",
                    f"Dylan thesis/tracking-sheet nmap: {clean_float(entry.get('dylan_nmap'))}",
                    "",
                    "Included fit products in this deck:",
                ]
                for e in grb_entries:
                    lines.append(f"- {e['display']}: nmap={clean_float(e.get('nmap'))}, k={clean_float(e.get('k'))}")
                add_text_box(fig, [0.12, 0.2, 0.76, 0.58], "\n".join(lines), fontsize=15)
                save_slide(pdf, fig)

            fig = make_slide(pdf, f"{entry['grb']} - Fit Summary", entry["display"])
            add_text_box(fig, [0.06, 0.11, 0.88, 0.76], title_text(entry), fontsize=12.2)
            add_footer(fig, str(entry["run_dir"]))
            save_slide(pdf, fig)

            fig = make_slide(pdf, f"{entry['grb']} - Light Curve", entry["display"])
            add_image_box(fig, [0.05, 0.12, 0.43, 0.72], entry["light_curve"], "VegasAfterglow fit light curve")
            add_image_box(
                fig,
                [0.52, 0.12, 0.43, 0.72],
                None,
                "Dylan thesis light curve",
                "Standalone Dylan thesis light-curve panel was not found locally for this build.",
            )
            add_footer(fig, str(entry["run_dir"]))
            save_slide(pdf, fig)

            fig = make_slide(pdf, f"{entry['grb']} - Spectral Breaks: Old vs New", entry["display"])
            legacy = entry["legacy_spectral"] if entry["legacy_spectral"].exists() else None
            add_image_box(
                fig,
                [0.12, 0.51, 0.76, 0.33],
                legacy,
                "OLD spectral-break plot - probably wrong",
                "Legacy old plot was not preserved before this batch overwrite. Treat prior spectral-break interpretations with caution.",
                fill=True,
            )
            add_image_box(
                fig,
                [0.12, 0.10, 0.76, 0.33],
                entry["spectral"],
                "NEW spectral-break plot - Dylan-style EATS weighted (Equal-Arrival-Time Surface)",
                fill=True,
            )
            add_footer(fig, str(entry["run_dir"]))
            save_slide(pdf, fig)

            fig = make_slide(pdf, f"{entry['grb']} - Spectral Breaks: Dylan vs New", entry["display"])
            add_image_box(
                fig,
                [0.12, 0.51, 0.76, 0.33],
                None,
                "Dylan thesis spectral-break plot",
                "Standalone Dylan thesis spectral-break panel was not found locally for this build.",
                fill=True,
            )
            add_image_box(
                fig,
                [0.12, 0.10, 0.76, 0.33],
                entry["spectral"],
                "NEW spectral-break plot - Dylan-style EATS weighted (Equal-Arrival-Time Surface)",
                fill=True,
            )
            add_footer(fig, str(entry["run_dir"]))
            save_slide(pdf, fig)

            fig = make_slide(pdf, f"{entry['grb']} - Parameter Comparison", entry["display"])
            add_image_box(
                fig,
                [0.08, 0.11, 0.84, 0.74],
                entry["ampy_comparison"],
                "log10(VegasAfterglow fit / AMPy thesis value)",
                "ampy_comparison.pdf not found for this fit folder.",
            )
            add_footer(fig, str(entry["run_dir"]))
            save_slide(pdf, fig)

            fig = make_slide(pdf, f"{entry['grb']} - Corner Plot", entry["display"])
            add_image_box(fig, [0.05, 0.12, 0.43, 0.72], entry["corner"], "VegasAfterglow posterior corner")
            add_image_box(
                fig,
                [0.52, 0.12, 0.43, 0.72],
                None,
                "Dylan / AMPy corner",
                "Standalone Dylan corner panel was not found locally for this build.",
            )
            add_footer(fig, str(entry["run_dir"]))
            save_slide(pdf, fig)

            fig = make_slide(pdf, f"{entry['grb']} - Science Notes", entry["display"])
            add_text_box(
                fig,
                [0.08, 0.12, 0.84, 0.72],
                (
                    "Meeting notes to add:\n\n"
                    "- Does the new EATS-weighted break-frequency plot change our interpretation of the light curve? EATS = Equal-Arrival-Time Surface.\n"
                    "- Are the data mostly before or after the relevant deceleration/free-expansion transition?\n"
                    "- Are k, theta_c, theta_v, Gamma0, or microphysical parameters pinned by bounds or strongly shifted from AMPy?\n"
                    "- Follow-up actions:"
                ),
                fontsize=15,
            )
            save_slide(pdf, fig)


def write_manifest(entries: list[dict], skipped: list[dict]):
    included_lines = [
        "| GRB | Fit type | nmap | Dylan nmap | k | Dylan k | spectral mtime | run folder |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for e in entries:
        included_lines.append(
            "| {grb} | {display} | {nmap} | {dnmap} | {k} | {dk} | {mtime} | `{run}` |".format(
                grb=e["grb"],
                display=e["display"],
                nmap=clean_float(e.get("nmap")),
                dnmap=clean_float(e.get("dylan_nmap")),
                k=clean_float(e.get("k")),
                dk=clean_float(e.get("dylan_k")),
                mtime=e["mtime"].strftime("%Y-%m-%d %H:%M:%S") if e.get("mtime") else "unavailable",
                run=e["run_dir"],
            )
        )

    skipped_lines = [
        "| GRB | Fit type | Reason | run root |",
        "| --- | --- | --- | --- |",
    ]
    for s in skipped:
        if s["reason"] != "new EATS-weighted spectral plot not finished":
            continue
        skipped_lines.append(f"| {s.get('grb')} | {s['display']} | {s['reason']} | `{s['run_root']}` |")

    text = "\n".join(
        [
            "# Break-Frequency Meeting Deck Manifest",
            "",
            f"Built: {dt.datetime.now().isoformat(timespec='seconds')}",
            f"Deck: `{OUT_PDF}`",
            "",
            "Selection rule: include a run only if `spectral_plot.pdf` was modified after "
            f"{UPDATED_AFTER.isoformat(sep=' ')} or if `spectral_breaks_eats_weighted.csv` exists.",
            "",
            "Definition: EATS = Equal-Arrival-Time Surface.",
            "",
            "Important caveat: most old legacy spectral-break plots were overwritten by the batch updater without a backup. "
            "Only folders with `spectral_plot_legacy_before_eats_weighted.pdf` have true old-vs-new visual comparison slides.",
            "",
            "## Included",
            "",
            "\n".join(included_lines),
            "",
            "## Skipped Because Weighted Plot Was Not Finished",
            "",
            "\n".join(skipped_lines),
            "",
        ]
    )
    OUT_MANIFEST.write_text(text)


def main():
    entries, skipped = discover_entries()
    build_deck(entries, skipped)
    write_manifest(entries, skipped)
    print(f"wrote {OUT_PDF}")
    print(f"wrote {OUT_MANIFEST}")
    print(f"included {len(entries)} fit products; skipped {len(skipped)}")


if __name__ == "__main__":
    main()
